// Download the Google Fonts the site uses into public/fonts/ and generate
// public/fonts.css with local @font-face rules — so no request ever reaches
// Google (DSGVO: no visitor-IP transfer to the US / LG München pattern).
//
// Run: node scripts/fetch-fonts.mjs   (re-run to refresh the woff2 files)
// Keeps only the latin + latin-ext subsets (covers German incl. äöüß/ß).

import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const FONTS_DIR = resolve(root, "public/fonts");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
const KEEP = new Set(["latin", "latin-ext"]);

const FAMILIES = [
  {
    name: "Cormorant Garamond",
    // 600/700 added for the playbook headings (migrated off Fraunces); 300-500
    // + italics 300/400 cover index/pro.
    url: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&display=swap",
  },
  {
    name: "DM Sans",
    url: "https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500&display=swap",
  },
  {
    name: "JetBrains Mono",
    url: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;700&display=swap",
  },
];

const slug = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

await mkdir(FONTS_DIR, { recursive: true });

let out =
  "/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs. Do not hand-edit. */\n";
const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g;

for (const fam of FAMILIES) {
  const css = await (await fetch(fam.url, { headers: { "User-Agent": UA } })).text();
  let m;
  while ((m = blockRe.exec(css))) {
    const subset = m[1];
    if (!KEEP.has(subset)) continue;
    let block = m[2];
    const style = (block.match(/font-style:\s*(\w+)/) || [])[1] || "normal";
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1] || "400";
    const urlMatch = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!urlMatch) continue;
    const fname = `${slug(fam.name)}-${weight}-${style}-${subset}.woff2`;
    const buf = Buffer.from(
      await (await fetch(urlMatch[1], { headers: { "User-Agent": UA } })).arrayBuffer()
    );
    await writeFile(resolve(FONTS_DIR, fname), buf);
    block = block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(/fonts/${fname})`);
    out += "\n" + block + "\n";
    console.log(`  ${fname} (${buf.length} bytes)`);
  }
}

await writeFile(resolve(root, "public/fonts.css"), out);
console.log("Wrote public/fonts.css");
